# -*- coding: utf-8 -*-
"""LungDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WNPcFIqOx-Qm16uJQQtQTrsmCu4lVND

## Thông tin nhóm
# ĐỀ TÀI 8: PHÁT HIỆN BỆNH PHỔI

**Nhóm:** [Tên nhóm 3-4 người]

**Thành viên:** Võ Hoàng Kim Ngân, Nhan Gia Huy

**GVHD:** Trần Trương Tuấn Phát

**Thư viện:** Scikit-learn, Pandas, Numpy, PyTorch, Keras

## CELL 1 — IMPORT THƯ VIỆN (DUY NHẤT)
"""

# CELL 1 — IMPORT THƯ VIỆN & CÀI ĐẶT (CHỈ CHẠY 1 LẦN)

import warnings
warnings.filterwarnings("ignore")

# ────────────────────────────────────────────────────────────────
# Import cơ bản
import os
import shutil
import glob
import numpy as np
from tqdm import tqdm
from pathlib import Path

# Hình ảnh & biểu đồ
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns

# Scikit-learn
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix

# TensorFlow / Keras
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Conv2DTranspose, concatenate, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# GPU config
physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print("GPU sẵn sàng")
else:
    print("Chạy trên CPU")

print(f"TensorFlow: {tf.__version__} | NumPy: {np.__version__}")

# Cài đặt thêm (nếu cần timm, xgboost, ... thì thêm sau)
print("Cài đặt một số gói bổ sung nếu cần...")
!pip install -q kagglehub timm

import kagglehub

print("\nHoàn tất Cell 1 – Thư viện sẵn sàng")

"""##Cell 1.5 - Set environment variable KAGGLE_API_TOKEN"""

# CELL 1.5 — KAGGLE API TOKEN (AN TOÀN)

from google.colab import userdata

KAGGLE_SECRET_NAME = "KAGGLE_API_TOKEN"   # ← Đổi tên secret nếu bạn đặt khác

try:
    kaggle_token = userdata.get(KAGGLE_SECRET_NAME)
    if not kaggle_token:
        raise ValueError("Secret rỗng")
except Exception as e:
    print("Không tìm thấy secret → dùng fallback (không khuyến khích)")
    kaggle_token = ""   # ← THAY BẰNG TOKEN CỦA BẠN NẾU CẦN (chỉ test)

os.environ['KAGGLE_USERNAME'] = "your_username"          # thay bằng username Kaggle của bạn
os.environ['KAGGLE_KEY'] = kaggle_token

# Kiểm tra nhanh
try:
    !kaggle datasets list -m --sort-by 'hottest' --max-size 1
    print("Kaggle API hoạt động bình thường")
except Exception as e:
    print("Lỗi Kaggle API:", str(e))
    print("→ Kiểm tra lại secret hoặc regenerate token trên Kaggle")

"""##Cell 1.7 - Download dataset weights U-Net"""

# CELL 1.7 — TẢI WEIGHTS U-NET LUNG SEGMENTATION

from pathlib import Path

DATASET_SLUG = "farhanhaikhan/unet-lung-segmentation-weights-for-chest-x-rays"
TARGET_DIR = Path("/content/unet_weights")
WEIGHTS_FILE = "cxr_reg_weights.best.hdf5"

if TARGET_DIR.exists() and (TARGET_DIR / WEIGHTS_FILE).exists():
    print(f"Đã có weights → skip tải: {TARGET_DIR / WEIGHTS_FILE}")
else:
    print(f"Đang tải dataset: {DATASET_SLUG}")
    !kaggle datasets download -d {DATASET_SLUG} -p {TARGET_DIR} --unzip --force
    print("Download & unzip xong")

weights_path = TARGET_DIR / WEIGHTS_FILE
if weights_path.exists():
    print(f"Found weights: {weights_path} ({weights_path.stat().st_size / (1024**2):.1f} MB)")
else:
    print("Không tìm thấy file weights mong đợi!")
    !ls -lh {TARGET_DIR}

"""## CELL 2 — TẢI DATASET VÀ CHUẨN BỊ THƯ MỤC"""

# CELL 2 — TẢI DATASET 4 LỚP

DATASET_SLUG = "jtiptj/chest-xray-pneumoniacovid19tuberculosis"
DATA_DIR = Path("data")
TRAIN_DIR = DATA_DIR / "train"
TEST_DIR = DATA_DIR / "test"

if TRAIN_DIR.exists() and TEST_DIR.exists() and any(TRAIN_DIR.iterdir()):
    print("Dataset đã tồn tại → skip tải")
else:
    print(f"Đang tải dataset: {DATASET_SLUG}")
    dataset_path = kagglehub.dataset_download(DATASET_SLUG)
    print(f"Dataset tải về: {dataset_path}")

    if DATA_DIR.exists():
        shutil.rmtree(DATA_DIR)
    DATA_DIR.mkdir(exist_ok=True)

    shutil.copytree(Path(dataset_path) / "train", TRAIN_DIR, dirs_exist_ok=True)
    shutil.copytree(Path(dataset_path) / "test", TEST_DIR, dirs_exist_ok=True)
    print("Copy train/test xong")

# Thống kê nhanh
print("\nTHỐNG KÊ DATASET")
for split, dir_path in [("train", TRAIN_DIR), ("test", TEST_DIR)]:
    print(f"\n{split.upper()}:")
    total = 0
    for cls in sorted(dir_path.iterdir()):
        if cls.is_dir():
            cnt = len(list(cls.glob("*.*")))
            print(f"  {cls.name:12} : {cnt:5d} ảnh")
            total += cnt
    print(f"  Tổng: {total} ảnh")

"""## CELL 2.2 — TẢI U-NET PRE-TRAINED + TẠO MASKED DATASET"""

# CELL 2.5 — U-NET LUNG SEGMENTATION (tạo data_masked)

MASKED_DIR = Path('data_masked')
ORIGINAL_DIR = Path('data')

if MASKED_DIR.exists():
    print("Xóa data_masked cũ...")
    shutil.rmtree(MASKED_DIR)
MASKED_DIR.mkdir(exist_ok=True)

# ── Xây U-Net ────────────────────────────────────────────────────────
def build_unet(input_size=(256, 256, 1)):
    inputs = Input(input_size)
    c1 = Conv2D(32, 3, activation='relu', padding='same')(inputs); c1 = Conv2D(32, 3, activation='relu', padding='same')(c1)
    p1 = MaxPooling2D((2,2))(c1)
    c2 = Conv2D(64, 3, activation='relu', padding='same')(p1); c2 = Conv2D(64, 3, activation='relu', padding='same')(c2)
    p2 = MaxPooling2D((2,2))(c2)
    c3 = Conv2D(128, 3, activation='relu', padding='same')(p2); c3 = Conv2D(128, 3, activation='relu', padding='same')(c3)
    p3 = MaxPooling2D((2,2))(c3)
    c4 = Conv2D(256, 3, activation='relu', padding='same')(p3); c4 = Conv2D(256, 3, activation='relu', padding='same')(c4)
    d4 = Dropout(0.5)(c4); p4 = MaxPooling2D((2,2))(d4)
    c5 = Conv2D(512, 3, activation='relu', padding='same')(p4); c5 = Conv2D(512, 3, activation='relu', padding='same')(c5)
    d5 = Dropout(0.5)(c5)

    u6 = Conv2DTranspose(256, 2, strides=(2,2), padding='same')(d5)
    m6 = concatenate([d4, u6]); c6 = Conv2D(256, 3, activation='relu', padding='same')(m6); c6 = Conv2D(256, 3, activation='relu', padding='same')(c6)

    u7 = Conv2DTranspose(128, 2, strides=(2,2), padding='same')(c6)
    m7 = concatenate([c3, u7]); c7 = Conv2D(128, 3, activation='relu', padding='same')(m7); c7 = Conv2D(128, 3, activation='relu', padding='same')(c7)

    u8 = Conv2DTranspose(64, 2, strides=(2,2), padding='same')(c7)
    m8 = concatenate([c2, u8]); c8 = Conv2D(64, 3, activation='relu', padding='same')(m8); c8 = Conv2D(64, 3, activation='relu', padding='same')(c8)

    u9 = Conv2DTranspose(32, 2, strides=(2,2), padding='same')(c8)
    m9 = concatenate([c1, u9]); c9 = Conv2D(32, 3, activation='relu', padding='same')(m9); c9 = Conv2D(32, 3, activation='relu', padding='same')(c9)
    outputs = Conv2D(1, 1, activation='sigmoid')(c9)

    return Model(inputs, outputs)

segment_model = build_unet()
segment_model.load_weights('/content/unet_weights/cxr_reg_weights.best.hdf5')
print("U-Net weights loaded.")

# ── Hàm mask ─────────────────────────────────────────────────────────
def apply_lung_mask(img_path):
    try:
        gray = Image.open(img_path).convert('L').resize((256,256))
        arr = np.array(gray)[None,...,None] / 255.0
        mask = segment_model.predict(arr, verbose=0)[0]
        mask = (mask > 0.3).astype(np.float32)

        mask_r = tf.image.resize(mask, (224,224)).numpy()
        mask_r = np.repeat(mask_r, 3, -1)

        orig = Image.open(img_path).convert('RGB').resize((224,224))
        orig_arr = np.array(orig) / 255.0
        masked = orig_arr * mask_r
        return (masked * 255).astype(np.uint8)
    except:
        return None

# ── Chạy segmentation ────────────────────────────────────────────────
for split in ['train', 'test']:
    src = ORIGINAL_DIR / split
    dst = MASKED_DIR / split
    if not src.exists(): continue
    dst.mkdir(parents=True, exist_ok=True)

    for cls_dir in src.iterdir():
        if not cls_dir.is_dir(): continue
        dst_cls = dst / cls_dir.name
        dst_cls.mkdir(exist_ok=True)

        images = sum([list(cls_dir.glob(pat)) for pat in ['*.jpg','*.jpeg','*.png','*.JPG','*.JPEG','*.PNG']], [])
        print(f"{split}/{cls_dir.name}: {len(images)} ảnh")

        for p in tqdm(images, desc=cls_dir.name):
            masked = apply_lung_mask(p)
            if masked is not None:
                Image.fromarray(masked).save(dst_cls / p.name)

print("\nHoàn tất tạo data_masked!")

"""##Cell 2.3 - Thư mục bổ sung Data"""

#Cell 2.3 - Thư mục bổ sung Data
import os
from pathlib import Path
import shutil

# Tạo thư mục bổ sung
supplement_dir = Path('supplement_data')
supplement_dir.mkdir(exist_ok=True)

# Tạo thư mục cho từng lớp trong supplement
for cls in ['NORMAL', 'TUBERCULOSIS']:
    (supplement_dir / cls).mkdir(exist_ok=True)

# Đảm bảo thư mục đích trong data_masked/train tồn tại
masked_train = Path('data_masked/train')
for cls in ['NORMAL', 'TUBERCULOSIS']:
    (masked_train / cls).mkdir(exist_ok=True)

print("✅ Đã tạo các thư mục bổ sung và đích.")
print("Cấu trúc hiện tại:")
for cls in ['NORMAL', 'TUBERCULOSIS']:
    cnt = len(list((masked_train / cls).glob('*.*')))
    print(f"  {cls:12} : {cnt} ảnh")

"""##Cell 2.4 - Tải Dataset bổ sung"""

##Cell 2.4 - Tải Dataset bổ sung
# Tải dataset Tuberculosis (Lao phổi)
print("Đang tải Tuberculosis dataset...")
!kaggle datasets download -d tawsifurrahman/tuberculosis-tb-chest-xray-dataset -p supplement_data --unzip -q

# Tải dataset Chest X-ray Pneumonia (để lấy thêm NORMAL)
print("Đang tải Chest X-ray Pneumonia dataset...")
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia -p supplement_data --unzip -q

print("✅ Hoàn tất tải dataset bổ sung!")

"""##Cell 2.5 - Lấy ảnh bổ sung để train/test"""

##Cell 2.5 - Lấy ảnh bổ sung để train/test
from pathlib import Path
import shutil
import glob

supplement_path = Path('supplement_data')
masked_train = Path('data_masked/train')

print("=== Bắt đầu copy dữ liệu bổ sung ===")

# 1. Copy Tuberculosis
tb_source_dirs = [
    supplement_path / 'TB_Chest_Radiography_Database' / 'Tuberculosis',
    supplement_path / 'TB Chest X-ray' / 'TB'
]

tb_files = []
for src_dir in tb_source_dirs:
    if src_dir.exists():
        tb_files.extend(list(src_dir.glob('*.png')) + list(src_dir.glob('*.jpg')) + list(src_dir.glob('*.jpeg')))

tb_files = tb_files[:450]   # giới hạn 450 ảnh

for f in tb_files:
    dest_path = masked_train / 'TUBERCULOSIS' / f.name
    shutil.copy(f, dest_path)

print(f"✅ Đã copy {len(tb_files)} ảnh vào TUBERCULOSIS")

# 2. Copy NORMAL
normal_source = supplement_path / 'chest_xray' / 'train' / 'NORMAL'
if normal_source.exists():
    normal_files = list(normal_source.glob('*.jpeg')) + list(normal_source.glob('*.jpg'))
    normal_files = normal_files[:550]   # lấy khoảng 550 ảnh

    for f in normal_files:
        dest_path = masked_train / 'NORMAL' / f.name
        shutil.copy(f, dest_path)

    print(f"✅ Đã copy {len(normal_files)} ảnh vào NORMAL")
else:
    print("⚠️ Không tìm thấy thư mục NORMAL từ chest-xray-pneumonia")

# Kiểm tra sau khi copy
print("\n=== Kiểm tra sau khi bổ sung ===")
for cls in ['NORMAL', 'TUBERCULOSIS']:
    cnt = len(list((masked_train / cls).glob('*.*')))
    print(f"{cls:12} : {cnt} ảnh")

"""##Cell 2.6 – Kiểm tra số lượng trước / sau segmentation"""

# CELL 2.6 — KIỂM TRA SỐ LƯỢNG ẢNH TRƯỚC / SAU SEGMENTATION

def count_images(root_dir):
    stats = {}
    total = 0
    if not os.path.exists(root_dir):
        return {}, 0
    for cls in sorted(os.listdir(root_dir)):
        p = os.path.join(root_dir, cls)
        if os.path.isdir(p):
            cnt = len([f for f in os.listdir(p) if f.lower().endswith(('.png','.jpg','.jpeg'))])
            stats[cls] = cnt
            total += cnt
    return stats, total

print("=== ORIGINAL data/train ===")
orig_stats, orig_total = count_images('data/train')
for k, v in orig_stats.items():
    print(f"{k:15} : {v:6d}")
print(f"Tổng: {orig_total}\n")

print("=== MASKED data_masked/train ===")
mask_stats, mask_total = count_images('data_masked/train')
for k, v in mask_stats.items():
    print(f"{k:15} : {v:6d}")
print(f"Tổng: {mask_total}\n")

if orig_total == mask_total and mask_total > 0 and all(v > 0 for v in mask_stats.values()):
    print("→ Segmentation thành công: số lượng khớp & không lớp nào bị thiếu!")
else:
    print("→ Cảnh báo: Có sự khác biệt hoặc một số lớp bị thiếu → kiểm tra lại!")

"""##CELL 2.7 — TIỀN XỬ LÝ DỮ LIỆU"""

# CELL 2.7 — TIỀN XỬ LÝ DỮ LIỆU (ĐÃ SỬA GLOB - CHẠY LẠI SAU KHI CÓ data_masked)

import os
import glob
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

train_dir = 'data_masked/train'

print("=== CELL 2.7: KIỂM TRA VÀ TÍNH CLASS WEIGHT ===")

if not os.path.exists(train_dir):
    print("❌ Chưa có thư mục data_masked/train!")
else:
    classes = sorted([d for d in os.listdir(train_dir) if os.path.isdir(os.path.join(train_dir, d))])
    print(f"Các lớp tìm thấy: {classes}\n")

    y_train = []
    file_counts = {}

    for i, cls in enumerate(classes):
        # Pattern glob mạnh hơn - bắt tất cả jpg, jpeg, png (không phân biệt hoa thường)
        patterns = [
            os.path.join(train_dir, cls, '*.jpg'),
            os.path.join(train_dir, cls, '*.jpeg'),
            os.path.join(train_dir, cls, '*.png'),
            os.path.join(train_dir, cls, '*.JPG'),
            os.path.join(train_dir, cls, '*.JPEG'),
            os.path.join(train_dir, cls, '*.PNG')
        ]

        files = []
        for pat in patterns:
            files.extend(glob.glob(pat))

        count = len(files)
        file_counts[cls] = count
        y_train.extend([i] * count)

        print(f"{cls:12} : {count:6d} ảnh")

    print(f"\nTổng ảnh train: {len(y_train)}")

    if len(y_train) > 0 and len(set(y_train)) == 4:
        class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
        # Boost nhẹ cho lớp ít ảnh
        class_weight_dict = {i: w * 1.3 for i, w in enumerate(class_weights)}

        print("\n✅ Class weights thực tế (boost x1.3 cho lớp thiểu số):")
        for i, cls in enumerate(classes):
            print(f"  {cls:12} (index {i}): {class_weight_dict[i]:.3f}")
    else:
        print("\n⚠️  Cảnh báo: Không đủ 4 lớp hoặc không có ảnh → kiểm tra lại Cell 2.5")

"""##CELL DEBUG: Kiểm tra và sửa số lớp trong data_masked/train"""

from pathlib import Path
import shutil

train_dir = Path('data_masked/train')

source_dir = train_dir / 'TURBERCULOSIS'   # thư mục sai chính tả
target_dir = train_dir / 'TUBERCULOSIS'   # thư mục đúng

if source_dir.exists():
    print(f"Đang dồn ảnh từ '{source_dir.name}' sang '{target_dir.name}'...")

    # Copy tất cả file từ thư mục sai sang thư mục đúng
    for file in source_dir.iterdir():
        if file.is_file():
            shutil.copy2(file, target_dir / file.name)

    num_moved = len(list(source_dir.iterdir()))
    print(f"✅ Đã chuyển {num_moved} ảnh từ TURBERCULOSIS sang TUBERCULOSIS")

    # Xóa thư mục thừa
    shutil.rmtree(source_dir)
    print(f"✅ Đã xóa thư mục thừa: {source_dir.name}")
else:
    print("Không tìm thấy thư mục TURBERCULOSIS")

# Kiểm tra lại
print("\nKiểm tra sau khi dồn:")
for cls in sorted([d.name for d in train_dir.iterdir() if d.is_dir()]):
    count = len(list((train_dir / cls).iterdir()))
    print(f"  {cls:15} : {count} ảnh")

"""##Cell kiểm tra 1: Xem thư mục data_masked/train có những lớp nào?"""

import os

masked_train = 'data_masked/train'

if not os.path.exists(masked_train):
    print("❌ Thư mục data_masked/train KHÔNG tồn tại!")
else:
    folders = [d for d in os.listdir(masked_train) if os.path.isdir(os.path.join(masked_train, d))]
    print("Các thư mục lớp hiện có trong data_masked/train:")
    print(folders if folders else "→ Rỗng hoàn toàn!")

    for folder in folders:
        path = os.path.join(masked_train, folder)
        count = len([f for f in os.listdir(path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
        print(f"  {folder:15} → {count} ảnh")

"""##Cell kiểm tra 2: So sánh số lượng gốc vs masked"""

import os

def quick_count(base):
    if not os.path.exists(base): return "Không tồn tại"
    return {d: len(os.listdir(os.path.join(base, d))) for d in os.listdir(base) if os.path.isdir(os.path.join(base, d))}

print("data/train:", quick_count('data/train'))
print("data_masked/train:", quick_count('data_masked/train'))

"""##Cell kiểm tra 3: Xem tên lớp thật sự trong data gốc (để phát hiện lỗi typo)"""

import os

print("Các thư mục trong data/train:")
print(os.listdir('data/train') if os.path.exists('data/train') else "Không tồn tại")

"""## CELL 3 - TRAIN MÔ HÌNH PHÂN LOẠI 3 BỆNH PHỔI (TẠM DỪNG)"""

# CELL 3 — TRAIN MÔ HÌNH (MOBILENETV2 + FOCAL LOSS + CLASS WEIGHT BOOST + VISUALIZE)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dropout, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix
import os
from collections import Counter

# ────────────────────────────────────────────────────────────────
# Sử dụng masked nếu có
USE_MASKED = True
base_dir = 'data_masked' if USE_MASKED and os.path.exists('data_masked') else 'data'

train_dir = f'{base_dir}/train'
test_dir = f'{base_dir}/test'

print(f"📂 Sử dụng thư mục: {base_dir}")

# ────────────────────────────────────────────────────────────────
# Data generators
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.3,
    horizontal_flip=True,
    fill_mode='nearest'
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

class_indices = train_generator.class_indices
print("\n🔑 Class indices:", class_indices)

# ────────────────────────────────────────────────────────────────
# Tính class weight THỦ CÔNG từ toàn bộ thư mục train (đảm bảo đủ 4 lớp)
print("\nĐếm số ảnh từng lớp từ thư mục train...")
class_counts = {}
for class_name in class_indices:
    class_path = os.path.join(train_dir, class_name)
    if os.path.exists(class_path):
        num_images = len([f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
        class_counts[class_name] = num_images
    else:
        class_counts[class_name] = 0

print("Số ảnh train mỗi lớp:")
for cls, cnt in class_counts.items():
    print(f"   {cls}: {cnt} ảnh")

total_samples = sum(class_counts.values())
class_weights = {}
for class_name, count in class_counts.items():
    if count == 0:
        class_weights[class_indices[class_name]] = 1.0  # tránh chia 0
    else:
        class_weights[class_indices[class_name]] = total_samples / (len(class_counts) * count)

class_weight_dict = class_weights
print("\n⚖️ Class weights gốc (tính thủ công):")
print(class_weight_dict)

# Boost thủ công - CHỈ ÁP DỤNG CHO LỚP TỒN TẠI
print("\nBoost thủ công:")
boost_factors = {
    'NORMAL': 5.0,
    'TUBERCULOSIS': 6.0,
    'COVID19': 0.5,
    'PNEUMONIA': 0.5
}

for class_name, factor in boost_factors.items():
    if class_name in class_indices:
        idx = class_indices[class_name]
        class_weight_dict[idx] *= factor
        print(f"   → {class_name} (index {idx}): nhân {factor}x")
    else:
        print(f"   → {class_name} không tồn tại → skip boost")

print("\n⚖️ Class weights sau boost:")
print(class_weight_dict)

# ────────────────────────────────────────────────────────────────
# TẢI MobileNetV2 với CACHE
print("\n📥 Tải hoặc load từ cache MobileNetV2 weights...")
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)
base_model.trainable = False
print("   → MobileNetV2 base loaded (weights cached)")

# ────────────────────────────────────────────────────────────────
# Build model head
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
predictions = Dense(len(class_indices), activation='softmax')(x)  # num_classes động

model = Model(inputs=base_model.input, outputs=predictions)

# Compile
model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss=tf.keras.losses.CategoricalFocalCrossentropy(alpha=0.25, gamma=2.0),
    metrics=['accuracy']
)

# Callbacks
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=12, restore_best_weights=True, mode='max'),
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=5, min_lr=1e-7, mode='max'),
    ModelCheckpoint('best_mobilenet_focal.keras', monitor='val_accuracy', save_best_only=True, mode='max')
]

# ────────────────────────────────────────────────────────────────
# Giai đoạn 1: Freeze base
print("\n🚀 Giai đoạn 1: Freeze base model...")
history1 = model.fit(
    train_generator,
    epochs=30,
    validation_data=test_generator,
    class_weight=class_weight_dict,
    callbacks=callbacks
)

# Giai đoạn 2: Fine-tune
print("\n🔓 Giai đoạn 2: Fine-tune...")
base_model.trainable = True
for layer in base_model.layers[:-100]:
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss=tf.keras.losses.CategoricalFocalCrossentropy(alpha=0.25, gamma=2.0),
    metrics=['accuracy']
)

history2 = model.fit(
    train_generator,
    epochs=30,
    validation_data=test_generator,
    class_weight=class_weight_dict,
    callbacks=callbacks
)

# ────────────────────────────────────────────────────────────────
# Đánh giá & visualize
print("\n📊 Đánh giá cuối cùng...")
test_loss, test_acc = model.evaluate(test_generator)
print(f"🎯 Test Accuracy: {test_acc*100:.2f}%")

# Confusion Matrix
test_preds = model.predict(test_generator, verbose=1)
test_preds_classes = np.argmax(test_preds, axis=1)
test_labels = test_generator.classes

cm = confusion_matrix(test_labels, test_preds_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=list(class_indices.keys()),
            yticklabels=list(class_indices.keys()))
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix - Test Set')
plt.show()

# Training history plot
acc = history1.history['accuracy'] + history2.history['accuracy']
val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']
loss = history1.history['loss'] + history2.history['loss']
val_loss = history1.history['val_loss'] + history2.history['val_loss']

epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training & Validation Accuracy')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training & Validation Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Lưu model cuối
model.save('lung_4_classes_focal.keras')
print("\n💾 Đã lưu model cuối: lung_4_classes_focal.keras")
print("   → Nếu vẫn thấy bias NORMAL/TUBERCULOSIS cao → tăng boost thêm hoặc chuyển sang Swin (Cell 3.5)")

"""##CELL 3.5 — TRAIN SWIN TRANSFORMER + MASKED IMAGES"""

# CELL 3.5 — CẢI TIẾN LẦN 2 (Tập trung khắc phục bias NORMAL)

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dropout, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Augmentation nhẹ, phù hợp với ảnh X-quang
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    width_shift_range=0.10,
    height_shift_range=0.10,
    zoom_range=0.10,
    horizontal_flip=True,
    brightness_range=[0.95, 1.05],
    fill_mode='nearest'
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    'data_masked/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)

test_gen = test_datagen.flow_from_directory(
    'data_masked/test',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

# Class weights - Tăng mạnh cho NORMAL, điều chỉnh lại các lớp khác
classes = np.unique(train_gen.classes)
class_weights_raw = compute_class_weight('balanced', classes=classes, y=train_gen.classes)

class_weight_dict = {
    0: class_weights_raw[0] * 2.2,   # COVID19
    1: class_weights_raw[1] * 3.2,   # NORMAL ← tăng mạnh
    2: class_weights_raw[2] * 0.85,  # PNEUMONIA
    3: class_weights_raw[3] * 2.8    # TUBERCULOSIS
}

print("Class weights mới (cải tiến):")
for i, name in enumerate(train_gen.class_indices.keys()):
    print(f"  {name:12}: {class_weight_dict[i]:.3f}")

# Xây dựng model
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.35)(x)
output = Dense(4, activation='softmax')(x)

model = Model(base_model.input, output)

model.compile(
    optimizer=Adam(learning_rate=8e-4),
    loss=tf.keras.losses.CategoricalFocalCrossentropy(alpha=0.25, gamma=2.0),
    metrics=['accuracy']
)

callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=10, restore_best_weights=True, mode='max'),
    ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=4, min_lr=1e-6, mode='max'),
    ModelCheckpoint('best_mobilenet_focal_v3.keras', monitor='val_accuracy', save_best_only=True)
]

# Giai đoạn 1: Freeze base
print("\n=== Giai đoạn 1: Freeze base ===")
history1 = model.fit(
    train_gen,
    epochs=20,
    validation_data=test_gen,
    class_weight=class_weight_dict,
    callbacks=callbacks
)

# Giai đoạn 2: Fine-tune
print("\n=== Giai đoạn 2: Fine-tune ===")
base_model.trainable = True
for layer in base_model.layers[:-90]:      # unfreeze nhiều hơn một chút
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=4e-5),
    loss=tf.keras.losses.CategoricalFocalCrossentropy(alpha=0.25, gamma=2.0),
    metrics=['accuracy']
)

history2 = model.fit(
    train_gen,
    epochs=15,
    validation_data=test_gen,
    class_weight=class_weight_dict,
    callbacks=callbacks
)

# Đánh giá cuối
test_loss, test_acc = model.evaluate(test_gen)
print(f"\n🎯 Test Accuracy sau cải tiến: {test_acc*100:.2f}%")

model.save('lung_detection_mobilenet_focal_improved_v2.keras')
print("Model đã được lưu!")

"""##CELL 3.6 — VISUALIZE & REPORT KẾT QUẢ"""

# CELL 3.6 — VISUALIZE & REPORT KẾT QUẢ (ĐÃ SỬA)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

print("="*60)
print("📊 ĐÁNH GIÁ CUỐI CÙNG TRÊN TEST SET")
print("="*60)

# Sử dụng test_gen từ Cell 3.5
test_loss, test_acc = model.evaluate(test_gen, verbose=0)
print(f"🎯 Test Accuracy: {test_acc*100:.2f}%")
print(f"   Test Loss:     {test_loss:.4f}")

# Dự đoán
y_pred = model.predict(test_gen, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = test_gen.classes

# Confusion Matrix
print("\nConfusion Matrix:")
cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(9, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=list(test_gen.class_indices.keys()),
            yticklabels=list(test_gen.class_indices.keys()),
            cbar=False, annot_kws={"size": 14})
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Test Set')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Classification Report
print("\nClassification Report (chi tiết từng lớp):")
report = classification_report(y_true, y_pred_classes,
                              target_names=list(test_gen.class_indices.keys()),
                              output_dict=True)

report_df = pd.DataFrame(report).transpose().round(3)
report_df.index.name = 'Class'
print(report_df)

# Tóm tắt
print("\nTóm tắt nhanh:")
print(f"• Accuracy:          {report['accuracy']*100:.2f}%")
print(f"• Macro Avg F1-score: {report['macro avg']['f1-score']*100:.2f}%")
print(f"• Weighted Avg F1:   {report['weighted avg']['f1-score']*100:.2f}%")

"""##Cell 3.7 - Grad-Cam"""

# CELL 3.7 — GRAD-CAM VISUALIZATION

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import backend as K
from PIL import Image
import glob
import os
from google.colab import files

# Hàm Grad-CAM
def get_gradcam_heatmap(model, img_array, class_idx, last_conv_layer_name='Conv_1'):
    grad_model = tf.keras.models.Model(
        [model.inputs],
        [model.get_layer(last_conv_layer_name).output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        loss = predictions[:, class_idx]

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = K.mean(grads, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]
    heatmap = tf.reduce_mean(tf.multiply(pooled_grads, conv_outputs), axis=-1)

    heatmap = tf.nn.relu(heatmap)
    heatmap /= tf.reduce_max(heatmap) + 1e-8
    return heatmap.numpy()

def display_gradcam(img_path, model, last_conv_layer_name='Conv_1', alpha=0.45):
    img = Image.open(img_path).convert('RGB').resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array_exp = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array_exp, verbose=0)[0]
    pred_idx = np.argmax(preds)
    pred_class_name = list(test_gen.class_indices.keys())[pred_idx]
    confidence = preds[pred_idx] * 100

    heatmap = get_gradcam_heatmap(model, img_array_exp, pred_idx, last_conv_layer_name)

    heatmap = np.uint8(255 * heatmap)
    heatmap = tf.image.resize(heatmap[..., np.newaxis], (224, 224)).numpy().squeeze()

    plt.figure(figsize=(15, 5))
    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title("Ảnh gốc")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(heatmap, cmap='jet')
    plt.title("Grad-CAM Heatmap")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(img)
    plt.imshow(heatmap, cmap='jet', alpha=alpha)
    plt.title(f"Dự đoán: {pred_class_name}\n({confidence:.1f}%)")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

# Sử dụng model hiện tại
print("Grad-CAM sẵn sàng! Model hiện tại:", model.name if hasattr(model, 'name') else "Custom Model")

# Test trên một số ảnh mẫu từ test set
print("\nTest Grad-CAM trên ảnh mẫu từ test set:")
test_base = 'data_masked/test'

for class_name in list(test_gen.class_indices.keys()):
    try:
        class_path = os.path.join(test_base, class_name)
        sample_img = glob.glob(os.path.join(class_path, '*.*'))[0]
        print(f"\n→ Lớp thật: {class_name}")
        display_gradcam(sample_img, model, last_conv_layer_name='Conv_1', alpha=0.45)
    except Exception as e:
        print(f"   Không tìm thấy ảnh cho lớp {class_name} hoặc lỗi: {e}")

print("\nNếu muốn test ảnh từ máy, hãy dùng phần upload bên dưới.")

"""## CELL 4 - KIỂM TRA DỰ ĐOÁN THỰC TẾ (TEST BIAS + UPLOAD ẢNH TỪ MÁY)"""

# CELL 4 — KIỂM TRA DỰ ĐOÁN THỰC TẾ & UPLOAD ẢNH TỪ MÁY

import os
import glob
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files
import tensorflow as tf

# Load model (nếu chưa load)
MODEL_PATH = 'lung_detection_mobilenet_focal_improved_v2.keras'   # thay tên nếu khác

if not os.path.exists(MODEL_PATH):
    MODEL_PATH = 'lung_detection_mobilenet_focal_final.keras'

model = tf.keras.models.load_model(MODEL_PATH)
print(f"✅ Đã load model: {MODEL_PATH}")

# Class names
class_names = list(test_gen.class_indices.keys())
print("Các lớp:", class_names)

# Phần 1: Test trên ảnh mẫu từ test set
print("\n=== Test trên ảnh mẫu từ data_masked/test ===")
test_base = 'data_masked/test'

for cls in class_names:
    try:
        sample_path = glob.glob(f"{test_base}/{cls}/*.*")[0]
        img = Image.open(sample_path).convert('RGB')
        plt.figure(figsize=(5,5))
        plt.imshow(img)
        plt.title(f"Ảnh mẫu - Lớp thật: {cls}")
        plt.axis('off')
        plt.show()

        img_resized = img.resize((224, 224))
        img_array = np.array(img_resized) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        pred = model.predict(img_array, verbose=0)[0]
        pred_idx = np.argmax(pred)
        confidence = pred[pred_idx] * 100

        print(f"Dự đoán: {class_names[pred_idx]} ({confidence:.2f}%)")
        print("Xác suất chi tiết:")
        for i, name in enumerate(class_names):
            print(f"   {name}: {pred[i]*100:.2f}%")
        print("-" * 50)
    except:
        print(f"Không tìm thấy ảnh mẫu cho lớp {cls}")

# Phần 2: Upload ảnh từ máy để test
print("\n=== Upload ảnh X-quang từ máy để test thực tế ===")
print("Hãy upload ảnh Normal, COVID19, Viêm phổi, Lao phổi để kiểm tra")

uploaded = files.upload()

for filename in uploaded.keys():
    print(f"\nĐang dự đoán: {filename}")
    img = Image.open(filename).convert('RGB')
    plt.figure(figsize=(5,5))
    plt.imshow(img)
    plt.title("Ảnh upload từ máy")
    plt.axis('off')
    plt.show()

    img_resized = img.resize((224, 224))
    img_array = np.array(img_resized) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    pred = model.predict(img_array, verbose=0)[0]
    pred_idx = np.argmax(pred)
    confidence = pred[pred_idx] * 100

    print(f"→ Dự đoán: {class_names[pred_idx]} ({confidence:.2f}%)")
    print("Xác suất chi tiết:")
    for i, name in enumerate(class_names):
        print(f"   {name}: {pred[i]*100:.2f}%")
    print("-" * 60)

"""## CELL 5: HUGGING FACE LOGIN"""

# CELL 5 – LOGIN VÀO HUGGING FACE (chạy 1 lần duy nhất)

!pip install -q huggingface_hub

from huggingface_hub import login

# Chạy dòng này → sẽ hiện ô paste token
login()

from huggingface_hub import whoami
whoami()  # Nếu OK: in username và role (write)

"""## CELL 6 : DOWNLOAD MÔ HÌNH & KIỂM TRA DỰ ĐOÁN NHANH"""

# CELL 6 — UPLOAD MODEL LÊN HUGGING FACE

from huggingface_hub import HfApi, create_repo, upload_file
import os

# ================== CÀI ĐẶT ==================
model_file = 'lung_detection_mobilenet_focal_improved_v2.keras'   # ← thay bằng tên file model thật của bạn nếu khác

repo_name = "lung-disease-detection"   # Bạn có thể đổi tên này

# Kiểm tra file tồn tại
if not os.path.exists(model_file):
    print(f"❌ Không tìm thấy file: {model_file}")
    print("Vui lòng kiểm tra lại tên file model!")
    print("Các file .keras hiện có:")
    !ls -lh *.keras
else:
    api = HfApi()
    username = api.whoami()['name']
    repo_id = f"{username}/{repo_name}"

    print(f"Đang tạo repo: {repo_id}")

    # Tạo repo
    create_repo(repo_id, exist_ok=True, repo_type="model")
    print("✅ Repo đã sẵn sàng")

    # Upload model
    print(f"Đang upload file {model_file} ... (có thể mất 1-5 phút tùy dung lượng)")

    upload_file(
        path_or_fileobj=model_file,
        path_in_repo=model_file,
        repo_id=repo_id,
        repo_type="model",
        commit_message="Upload final lung disease classification model - 91.57% accuracy"
    )

    print("\n🎉 UPLOAD THÀNH CÔNG!")
    print(f"🔗 Link repo của bạn: https://huggingface.co/{repo_id}")
    print(f"📥 Link tải trực tiếp model: https://huggingface.co/{repo_id}/resolve/main/{model_file}")

"""##Cell 7 - Cài đặt Git và thiết lập thông tin"""

#Cell 7 - Cài đặt Git và thiết lập thông tin
!git config --global user.name "Kim3424"
!git config --global user.email "nganvhk22@uef.edu.vn"

print("✅ Đã cập nhật Git config thành công!")
print("User name :", "Kim3424")
print("Email     :", "nganvhk22@uef.edu.vn")

"""##Cell 8 - Clone repository về Colab"""

# Commented out IPython magic to ensure Python compatibility.
# Cell 8: Clone repo GitHub về Colab
# Thay link repo của bạn vào đây (đã thay sẵn theo repo bạn tạo)

!git clone https://github.com/Kim3424/lung-disease-detection-2.git
# %cd lung-disease-detection-2

print("✅ Đã clone repository về Colab")

"""## Cell 9 - Copy notebook + tạo requirements.txt + README.md"""

# Cell 9: Copy notebook + tạo requirements.txt + README.md

import shutil
import os

# Tên notebook chính xác sau khi upload
notebook_name = 'LungDetection.ipynb'

if os.path.exists('/content/' + notebook_name):
    shutil.copy('/content/' + notebook_name, 'LungDetection.ipynb')
    print(f"✅ Đã copy notebook: {notebook_name} → LungDetection.ipynb")
else:
    print(f"⚠️ Không tìm thấy notebook '{notebook_name}'")

# Tạo requirements.txt
!pip freeze > requirements.txt
print("✅ Đã tạo requirements.txt")

# Tạo README.md
readme_content = """# Lung Disease Detection Project

Mô hình phát hiện 4 bệnh phổi từ ảnh X-quang ngực sử dụng Deep Learning.

**Kết quả đạt được:**
- Test Accuracy: **91.57%**
- Macro F1-score: **93.65%**

### Các lớp bệnh được phân loại:
- COVID19
- NORMAL
- PNEUMONIA
- TUBERCULOSIS

### Công nghệ sử dụng:
- MobileNetV2 + U-Net Lung Segmentation
- Focal Loss + Class Weight
- TensorFlow / Keras

### Thành viên nhóm:
- Võ Hoàng Kim Ngân
- Nhan Gia Huy
---

**Lưu ý**: Đây là dự án học thuật, chỉ mang tính chất tham khảo và hỗ trợ nghiên cứu.
"""

with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)

print("✅ Đã tạo README.md")

"""## Cell 10 - Commit và Push code lên GitHub"""

# Cell 4: Commit và Push code lên GitHub

!git add .
!git commit -m "Initial commit: Lung disease detection project - Accuracy 91.57%"

print("Đang push code lên GitHub...")

!git push origin main